// ═══════════════════════════════════════════════════
// 100 SCENARIOS — Mario at Home
// Each has: title, desc (for AI context), mood,
//   sign (door sign text), visitors[], action (what mario does),
//   items[] (objects in scene), timeOfDay, doorState
// ═══════════════════════════════════════════════════

const SCENARIOS = [
  // ─── 1-10: МАРИО ОДИН ───
  { id:1, title:"Марио один дома", desc:"Марио сидит на диване один. Тихо. Грустно. Телевизор показывает помехи.", mood:"грустный", sign:"", visitors:[], action:"sit-sad", items:["tv-static","pizza-box"], timeOfDay:"evening", doorState:"closed" },
  { id:2, title:"Марио готовит пасту", desc:"Марио на кухне варит пасту. Пар идёт, запах чеснока. Он напевает.", mood:"весёлый", sign:"", visitors:[], action:"cook", items:["pot","steam"], timeOfDay:"day", doorState:"closed" },
  { id:3, title:"Марио нет дома", desc:"Марио вышел за грибами. На двери табличка 'Марио нет дома'. Но слышно шорохи внутри.", mood:"хитрый", sign:"МАРИО НЕТ ДОМА", visitors:[], action:"hiding", items:["shoes-outside"], timeOfDay:"day", doorState:"closed" },
  { id:4, title:"Марио спит", desc:"Марио уснул на диване. Храпит громко. Из кепки вылетает Z.", mood:"сонный", sign:"ТИШЕ!", visitors:[], action:"sleep", items:["blanket","z-bubbles"], timeOfDay:"night", doorState:"closed" },
  { id:5, title:"Марио играет в приставку", desc:"Марио играет в свою же игру на NES. Ругается на себя за плохую игру.", mood:"раздражённый", sign:"", visitors:[], action:"gaming", items:["nes","gamepad"], timeOfDay:"evening", doorState:"closed" },
  { id:6, title:"Марио делает ремонт", desc:"Марио красит стены. Всё в краске — и он тоже. Катастрофа.", mood:"измотанный", sign:"РЕМОНТ!", visitors:[], action:"paint", items:["paint-bucket","ladder"], timeOfDay:"day", doorState:"open" },
  { id:7, title:"Марио читает письмо", desc:"Марио получил письмо от Пич. Перечитывает 10-й раз. На глазах слёзы.", mood:"романтичный", sign:"", visitors:[], action:"read-letter", items:["letter","heart"], timeOfDay:"evening", doorState:"closed" },
  { id:8, title:"Марио убирается", desc:"Марио пылесосит дом. Нашёл 47 монет под диваном. Откуда они?!", mood:"удивлённый", sign:"", visitors:[], action:"vacuum", items:["vacuum","coins-pile"], timeOfDay:"day", doorState:"closed" },
  { id:9, title:"Марио медитирует", desc:"Марио сидит в позе лотоса. Пытается достичь дзена. Слышит звук монеток в голове.", mood:"спокойный", sign:"НЕ БЕСПОКОИТЬ", visitors:[], action:"meditate", items:["candle","incense"], timeOfDay:"evening", doorState:"closed" },
  { id:10, title:"Марио заболел", desc:"Марио простудился. Лежит под одеялами. Нос красный — краснее кепки.", mood:"больной", sign:"КАРАНТИН", visitors:[], action:"sick", items:["thermometer","tissues","soup"], timeOfDay:"day", doorState:"closed" },

  // ─── 11-20: ЛУИДЖИ В ГОСТЯХ ───
  { id:11, title:"Луиджи пришёл в гости", desc:"Луиджи пришёл к Марио. Они сидят на диване и вспоминают приключения.", mood:"тёплый", sign:"", visitors:["luigi"], action:"sit-talk", items:["tea-cups","photo-album"], timeOfDay:"evening", doorState:"open" },
  { id:12, title:"Луиджи жалуется на привидений", desc:"Луиджи рассказывает как его опять напугали в особняке. Трясётся.", mood:"сочувствующий", sign:"", visitors:["luigi-scared"], action:"comfort", items:["flashlight","ghost-book"], timeOfDay:"night", doorState:"closed" },
  { id:13, title:"Братья играют в карты", desc:"Марио и Луиджи играют в карты. Марио жульничает, Луиджи подозревает.", mood:"весёлый", sign:"", visitors:["luigi"], action:"cards", items:["cards","coins-bet"], timeOfDay:"evening", doorState:"closed" },
  { id:14, title:"Луиджи привёз подарок", desc:"Луиджи привёз брату новый набор инструментов. Марио тронут до слёз.", mood:"растроганный", sign:"", visitors:["luigi-gift"], action:"hug", items:["gift-box","tools"], timeOfDay:"day", doorState:"open" },
  { id:15, title:"Братья ссорятся", desc:"Марио и Луиджи поссорились из-за того, кто лучший водопроводчик.", mood:"сердитый", sign:"", visitors:["luigi-angry"], action:"argue", items:["wrench","plunger"], timeOfDay:"day", doorState:"open" },
  { id:16, title:"Луиджи ночует у Марио", desc:"Луиджи остался ночевать. Храпят оба. Дом трясётся.", mood:"уютный", sign:"", visitors:["luigi-sleep"], action:"sleep-both", items:["two-blankets","pillow-fight"], timeOfDay:"night", doorState:"closed" },
  { id:17, title:"Луиджи учит Марио танцевать", desc:"Луиджи показывает новый танец. Марио пытается повторить — ломает вазу.", mood:"весёлый", sign:"ВЕЧЕРИНКА", visitors:["luigi-dance"], action:"dance-fail", items:["music-notes","broken-vase"], timeOfDay:"evening", doorState:"closed" },
  { id:18, title:"Братья смотрят кино", desc:"Марио и Луиджи смотрят ужастик. Оба прячутся за подушками.", mood:"испуганный", sign:"", visitors:["luigi"], action:"watch-movie", items:["tv-horror","popcorn","pillows"], timeOfDay:"night", doorState:"closed" },
  { id:19, title:"Луиджи приготовил ужин", desc:"Луиджи приготовил своё фирменное ризотто. Марио пробует — это шедевр.", mood:"счастливый", sign:"", visitors:["luigi-chef"], action:"eat-together", items:["risotto","wine-glasses"], timeOfDay:"evening", doorState:"closed" },
  { id:20, title:"Луиджи прощается", desc:"Луиджи уходит домой. Братья обнимаются на пороге. Трогательно.", mood:"тёплый", sign:"", visitors:["luigi-leaving"], action:"wave-goodbye", items:["door-open","sunset"], timeOfDay:"evening", doorState:"open" },

  // ─── 21-30: ПИЧ И РОМАНТИКА ───
  { id:21, title:"Пич звонит по телефону", desc:"Пич позвонила Марио. Он нервно крутит усы. Краснеет.", mood:"взволнованный", sign:"", visitors:[], action:"phone-call", items:["phone","hearts"], timeOfDay:"evening", doorState:"closed" },
  { id:22, title:"Марио расстался с Пич", desc:"Пич бросила Марио. Он сидит с мороженым и смотрит их фото.", mood:"разбитый", sign:"НЕ БЕСПОКОИТЬ", visitors:[], action:"eat-icecream", items:["icecream","photos","tissues"], timeOfDay:"night", doorState:"closed" },
  { id:23, title:"Пич пришла мириться", desc:"Пич стоит у двери с тортом. Марио не знает — открывать или нет.", mood:"растерянный", sign:"", visitors:["peach-door"], action:"peek-door", items:["cake","flowers"], timeOfDay:"day", doorState:"half" },
  { id:24, title:"Романтический ужин", desc:"Марио накрыл стол для двоих. Свечи, паста, розы. Ждёт Пич.", mood:"романтичный", sign:"ЗАРЕЗЕРВИРОВАНО", visitors:[], action:"set-table", items:["candles","roses","pasta"], timeOfDay:"evening", doorState:"closed" },
  { id:25, title:"Пич в гостях", desc:"Пич и Марио пьют чай на диване. Она рассказывает о делах в замке.", mood:"счастливый", sign:"", visitors:["peach"], action:"tea-time", items:["tea-set","crown-on-table"], timeOfDay:"day", doorState:"closed" },
  { id:26, title:"Марио пишет любовное письмо", desc:"Марио пытается написать письмо Пич. Вокруг скомканные черновики.", mood:"сосредоточенный", sign:"", visitors:[], action:"write-letter", items:["paper","crumpled-papers","pen"], timeOfDay:"night", doorState:"closed" },
  { id:27, title:"Марио ревнует", desc:"Марио увидел фото Пич с Варио в Грибном Инстаграме. В бешенстве.", mood:"ревнивый", sign:"", visitors:[], action:"angry-phone", items:["phone-crack","pillow-torn"], timeOfDay:"evening", doorState:"closed" },
  { id:28, title:"Свидание отменено", desc:"Пич отменила свидание. Марио стоит в костюме посреди комнаты. Один.", mood:"подавленный", sign:"", visitors:[], action:"stand-sad", items:["suit","wilted-flowers","clock"], timeOfDay:"evening", doorState:"closed" },
  { id:29, title:"Пич прислала подарок", desc:"Курьер-Тоад принёс посылку от Пич. Внутри — новая кепка и записка.", mood:"тронутый", sign:"", visitors:["toad-courier"], action:"open-gift", items:["package","new-hat","love-note"], timeOfDay:"day", doorState:"open" },
  { id:30, title:"Марио мечтает о Пич", desc:"Марио лежит и мечтает. В облачке над головой — Пич и замок.", mood:"мечтательный", sign:"", visitors:[], action:"daydream", items:["thought-bubble","cloud-peach"], timeOfDay:"day", doorState:"closed" },

  // ─── 31-40: ТОАД И ДРУЗЬЯ ───
  { id:31, title:"Тоад принёс грибы", desc:"Тоад пришёл с корзиной грибов. Марио рад — ужин будет!", mood:"радостный", sign:"", visitors:["toad"], action:"receive-gift", items:["mushroom-basket"], timeOfDay:"day", doorState:"open" },
  { id:32, title:"Тоад просит совета", desc:"Тоад влюбился и просит совета у Марио. Марио — плохой советчик.", mood:"неловкий", sign:"", visitors:["toad-love"], action:"awkward-advice", items:["heart-card","confused-face"], timeOfDay:"evening", doorState:"closed" },
  { id:33, title:"Йоши на заднем дворе", desc:"Йоши пришёл и ест яблоки на заднем дворе. Марио смотрит в окно.", mood:"умиротворённый", sign:"", visitors:["yoshi"], action:"look-window", items:["apples","window"], timeOfDay:"day", doorState:"closed" },
  { id:34, title:"Компания друзей", desc:"Тоад, Йоши и Марио играют в настолки. Шумно, весело.", mood:"весёлый", sign:"ВЕЧЕРИНКА!", visitors:["toad","yoshi"], action:"board-game", items:["board-game","snacks","dice"], timeOfDay:"evening", doorState:"closed" },
  { id:35, title:"Тоад пожаловался на работу", desc:"Тоад устал работать в замке. Хочет уволиться. Марио пытается поддержать.", mood:"серьёзный", sign:"", visitors:["toad-tired"], action:"heart-to-heart", items:["tea","tired-eyes"], timeOfDay:"night", doorState:"closed" },
  { id:36, title:"Розалина заглянула", desc:"Розалина залетела на звезде. Пьёт космический чай. Марио в шоке.", mood:"восхищённый", sign:"", visitors:["rosalina"], action:"stargazing", items:["star","cosmic-tea","sparkles"], timeOfDay:"night", doorState:"open" },
  { id:37, title:"Старые друзья", desc:"Донки Конг пришёл. Они вспоминают первую битву. Смеются.", mood:"ностальгический", sign:"", visitors:["dk"], action:"remember-old-times", items:["banana","barrel","old-photo"], timeOfDay:"evening", doorState:"open" },
  { id:38, title:"Крошка Тоад потерялся", desc:"Маленький Тоад заблудился и стучится к Марио. Марио пускает его.", mood:"заботливый", sign:"", visitors:["baby-toad"], action:"comfort-child", items:["milk","cookie","blanket"], timeOfDay:"night", doorState:"open" },
  { id:39, title:"Капитан Тоад рассказывает", desc:"Капитан Тоад рассказывает о своих экспедициях. Карты повсюду.", mood:"заинтересованный", sign:"", visitors:["captain-toad"], action:"look-at-maps", items:["maps","compass","treasure-chest"], timeOfDay:"evening", doorState:"closed" },
  { id:40, title:"Никто не пришёл", desc:"Марио ждал гостей на ужин. Накрыл стол на 5 человек. Никто не пришёл.", mood:"одинокий", sign:"ДОБРО ПОЖАЛОВАТЬ", visitors:[], action:"wait-alone", items:["set-table-5","clock-late","wilted-flowers"], timeOfDay:"night", doorState:"open" },

  // ─── 41-50: БОУЗЕР И ВРАГИ ───
  { id:41, title:"Боузер стучится в дверь", desc:"Боузер пришёл к Марио. Говорит что хочет поговорить. Марио не верит.", mood:"подозрительный", sign:"", visitors:["bowser-door"], action:"peek-careful", items:["chain-lock","peephole"], timeOfDay:"day", doorState:"half" },
  { id:42, title:"Боузер принёс торт", desc:"Боузер извиняется и принёс торт. Марио пробует — торт вкусный. Шок.", mood:"шокированный", sign:"", visitors:["bowser"], action:"eat-cake", items:["cake","truce-flag"], timeOfDay:"day", doorState:"open" },
  { id:43, title:"Гумбы за окном", desc:"Марио заметил что Гумбы ходят за окном. Много. Слишком много.", mood:"обеспокоенный", sign:"ЗАКРЫТО", visitors:[], action:"peek-window-scared", items:["binoculars","goombas-outside"], timeOfDay:"evening", doorState:"closed" },
  { id:44, title:"Боузер Джуниор убежал из дома", desc:"Боузер Джуниор пришёл к Марио — убежал от папы. Марио не знает что делать.", mood:"растерянный", sign:"", visitors:["bowser-jr"], action:"confused", items:["backpack","jr-drawing"], timeOfDay:"day", doorState:"open" },
  { id:45, title:"Варио взломал замок", desc:"Варио вломился и ищет монеты. Марио пытается его выгнать.", mood:"злой", sign:"ВЫЗВАНА ПОЛИЦИЯ", visitors:["wario"], action:"chase-away", items:["stolen-coins","broken-lock"], timeOfDay:"night", doorState:"broken" },
  { id:46, title:"Валуиджи хочет дружить", desc:"Валуиджи пришёл и просит дружбы. Очень неловко. Марио жалко.", mood:"сочувствующий", sign:"", visitors:["waluigi"], action:"awkward-tea", items:["tea","awkward-silence"], timeOfDay:"evening", doorState:"open" },
  { id:47, title:"Купа-Трупа с петицией", desc:"Купа-Трупа пришёл с петицией — хотят чтобы Марио прекратил прыгать на них.", mood:"виноватый", sign:"", visitors:["koopa"], action:"read-petition", items:["petition","pen","glasses"], timeOfDay:"day", doorState:"open" },
  { id:48, title:"Буллет Билл застрял в стене", desc:"Буллет Билл врезался в стену дома Марио. Торчит. Марио в панике.", mood:"в панике", sign:"ПОМОГИТЕ!", visitors:[], action:"panic", items:["bullet-in-wall","crack","dust"], timeOfDay:"day", doorState:"open" },
  { id:49, title:"Бу за шторой", desc:"Марио чувствует что за шторой кто-то есть. Это Бу. Он прячется.", mood:"испуганный", sign:"", visitors:["boo"], action:"scared", items:["curtain","ghost-eyes"], timeOfDay:"night", doorState:"closed" },
  { id:50, title:"Мирный договор", desc:"Боузер, Марио и Пич за столом переговоров. Обсуждают вечный мир.", mood:"дипломатичный", sign:"ПЕРЕГОВОРЫ", visitors:["bowser","peach"], action:"negotiate", items:["document","pen","handshake"], timeOfDay:"day", doorState:"closed" },

  // ─── 51-60: ЕДА И КУХНЯ ───
  { id:51, title:"Пицца на заказ", desc:"Марио заказал пиццу. Курьер — Лакиту на облаке. Пицца холодная.", mood:"разочарованный", sign:"", visitors:["lakitu-delivery"], action:"open-pizza", items:["pizza-box","cold-pizza"], timeOfDay:"evening", doorState:"open" },
  { id:52, title:"Пригорело!", desc:"Марио забыл про пасту на плите. Весь дом в дыму. Спасай ужин!", mood:"в панике", sign:"", visitors:[], action:"fire-extinguish", items:["smoke","burnt-pot","fire-ext"], timeOfDay:"evening", doorState:"open" },
  { id:53, title:"Марио печёт торт", desc:"Марио печёт торт на день рождения Луиджи. Получается криво но с душой.", mood:"старательный", sign:"", visitors:[], action:"bake", items:["flour","eggs","crooked-cake"], timeOfDay:"day", doorState:"closed" },
  { id:54, title:"Холодильник пустой", desc:"В холодильнике только огненный цветок и просроченное молоко.", mood:"голодный", sign:"", visitors:[], action:"sad-fridge", items:["empty-fridge","fire-flower","expired-milk"], timeOfDay:"night", doorState:"closed" },
  { id:55, title:"Грибной суп", desc:"Марио варит грибной суп. Проблема — грибы разговаривают.", mood:"этически-растерянный", sign:"", visitors:[], action:"cook-confused", items:["talking-mushroom","soup-pot"], timeOfDay:"day", doorState:"closed" },
  { id:56, title:"Итальянский ужин", desc:"Марио приготовил шикарный итальянский ужин. 7 блюд. Для себя одного.", mood:"гордый-но-одинокий", sign:"РЕСТОРАН МАРИО", visitors:[], action:"feast-alone", items:["7-dishes","wine","candelabra"], timeOfDay:"evening", doorState:"closed" },
  { id:57, title:"Марио на диете", desc:"Марио решил похудеть. Ест салат. Страдает. Мечтает о пасте.", mood:"страдающий", sign:"ДИЕТА", visitors:[], action:"eat-salad", items:["salad","diet-book","hidden-pasta"], timeOfDay:"day", doorState:"closed" },
  { id:58, title:"Кулинарный баттл", desc:"Марио и Луиджи устроили кулинарный баттл. Кухня в хаосе.", mood:"соревновательный", sign:"", visitors:["luigi-chef"], action:"cook-battle", items:["two-pots","mess","timer"], timeOfDay:"evening", doorState:"closed" },
  { id:59, title:"Марио ест грибы", desc:"Марио ест грибы и растёт. Упёрся головой в потолок. Опять.", mood:"раздосадованный", sign:"", visitors:[], action:"too-big", items:["ceiling-crack","mushroom-plate"], timeOfDay:"day", doorState:"closed" },
  { id:60, title:"Кофе утром", desc:"Марио пьёт утренний кофе. Тихо, спокойно. Первые минуты без хаоса.", mood:"умиротворённый", sign:"", visitors:[], action:"coffee", items:["coffee-cup","newspaper","sunrise"], timeOfDay:"morning", doorState:"closed" },

  // ─── 61-70: ХОББИ И УВЛЕЧЕНИЯ ───
  { id:61, title:"Марио рисует", desc:"Марио рисует портрет Пич. Получается как 8-битная версия.", mood:"творческий", sign:"", visitors:[], action:"paint-canvas", items:["easel","paints","pixel-portrait"], timeOfDay:"day", doorState:"closed" },
  { id:62, title:"Марио играет на гитаре", desc:"Марио учится играть на гитаре. Соседи стучат в стену.", mood:"увлечённый", sign:"", visitors:[], action:"guitar", items:["guitar","music-notes","angry-wall"], timeOfDay:"evening", doorState:"closed" },
  { id:63, title:"Марио смотрит сериал", desc:"Марио залип на сериал. 5-й сезон подряд. Не мылся 3 дня.", mood:"залипший", sign:"НЕ БЕСПОКОИТЬ", visitors:[], action:"binge-watch", items:["tv-series","snack-pile","messy-hair"], timeOfDay:"night", doorState:"closed" },
  { id:64, title:"Марио собирает пазл", desc:"Марио собирает пазл на 1000 деталей — карта Грибного Королевства.", mood:"сосредоточенный", sign:"", visitors:[], action:"puzzle", items:["puzzle-table","missing-piece"], timeOfDay:"evening", doorState:"closed" },
  { id:65, title:"Марио ведёт блог", desc:"Марио ведёт блог 'Записки водопроводчика'. 3 подписчика. Доволен.", mood:"довольный", sign:"", visitors:[], action:"typing", items:["laptop","blog-screen","3-followers"], timeOfDay:"night", doorState:"closed" },
  { id:66, title:"Марио чинит трубы", desc:"Марио чинит трубы дома. Наконец вспомнил что он водопроводчик.", mood:"профессиональный", sign:"САНТЕХРАБОТЫ", visitors:[], action:"fix-pipes", items:["wrench","pipes","water-splash"], timeOfDay:"day", doorState:"closed" },
  { id:67, title:"Марио занимается йогой", desc:"Марио в позе воина. Валится. Пытается снова. Опять валится.", mood:"упорный", sign:"", visitors:[], action:"yoga-fail", items:["yoga-mat","incense","fallen-pose"], timeOfDay:"morning", doorState:"closed" },
  { id:68, title:"Марио стримит", desc:"Марио стримит на Грибном Твиче. 4 зрителя. Один — бот.", mood:"энтузиастичный", sign:"LIVE", visitors:[], action:"streaming", items:["webcam","mic","chat-trolls"], timeOfDay:"night", doorState:"closed" },
  { id:69, title:"Марио садовничает", desc:"Марио посадил огненные цветы в горшки. Они начали стрелять фаерболами.", mood:"обеспокоенный", sign:"ОСТОРОЖНО", visitors:[], action:"dodge-fireballs", items:["flower-pots","fireballs","singed-hat"], timeOfDay:"day", doorState:"open" },
  { id:70, title:"Марио пишет мемуары", desc:"Марио пишет книгу 'Жизнь в трубах'. Застрял на главе про Боузера.", mood:"задумчивый", sign:"ТИШИНА", visitors:[], action:"writing", items:["typewriter","crumpled-paper","coffee"], timeOfDay:"night", doorState:"closed" },

  // ─── 71-80: ПРОБЛЕМЫ И НЕПРИЯТНОСТИ ───
  { id:71, title:"Потоп в доме", desc:"Труба лопнула. Вода везде. Ирония — водопроводчик с потопом.", mood:"в панике", sign:"НАВОДНЕНИЕ", visitors:[], action:"water-panic", items:["water-floor","buckets","mop"], timeOfDay:"day", doorState:"open" },
  { id:72, title:"Отключили свет", desc:"Электричество вырубилось. Марио в темноте. Слышны странные звуки.", mood:"испуганный", sign:"", visitors:[], action:"candle-dark", items:["candle","dark-room","scary-sounds"], timeOfDay:"night", doorState:"closed" },
  { id:73, title:"Посылка от незнакомца", desc:"Пришла странная посылка без обратного адреса. Тикает.", mood:"тревожный", sign:"", visitors:[], action:"inspect-box", items:["mystery-box","ticking","sweat"], timeOfDay:"day", doorState:"closed" },
  { id:74, title:"Соседи жалуются", desc:"Соседи-Гумбы написали жалобу. Марио слишком громко прыгает.", mood:"виноватый", sign:"ИЗВИНИТЕ", visitors:["goomba-neighbor"], action:"apologize", items:["complaint-letter","slippers"], timeOfDay:"evening", doorState:"open" },
  { id:75, title:"Мыши в доме", desc:"В доме завелись мыши. Маленькие Чип-Чипы. Марио визжит как Луиджи.", mood:"в панике", sign:"", visitors:[], action:"stand-on-chair", items:["chair","tiny-mice","broom"], timeOfDay:"night", doorState:"closed" },
  { id:76, title:"Потерял кепку", desc:"Марио не может найти кепку. Без неё чувствует себя голым.", mood:"потерянный", sign:"", visitors:[], action:"search-frantically", items:["messy-room","bald-mario","under-couch"], timeOfDay:"morning", doorState:"closed" },
  { id:77, title:"Счёт за монеты", desc:"Пришёл налог на 50,000 монет. Марио в шоке. Откуда такой счёт?!", mood:"шокированный", sign:"", visitors:[], action:"read-bill", items:["huge-bill","calculator","empty-wallet"], timeOfDay:"day", doorState:"closed" },
  { id:78, title:"Аллергия на грибы", desc:"Марио покрылся пятнами. Доктор Марио сказал — аллергия на грибы. Катастрофа.", mood:"отчаявшийся", sign:"КАРАНТИН", visitors:[], action:"scratching", items:["spots","medicine","no-mushroom-sign"], timeOfDay:"day", doorState:"closed" },
  { id:79, title:"WiFi не работает", desc:"Интернет пропал. Марио не может загрузить рецепт пасты. Крах мира.", mood:"раздражённый", sign:"", visitors:[], action:"angry-router", items:["router","no-signal","cookbook"], timeOfDay:"evening", doorState:"closed" },
  { id:80, title:"Землетрясение", desc:"Всё трясётся. Это Танос Тамп прыгает за окном. Посуда падает.", mood:"в панике", sign:"", visitors:[], action:"hold-on", items:["shaking","falling-plates","thwomp-outside"], timeOfDay:"day", doorState:"closed" },

  // ─── 81-90: ФИЛОСОФИЯ И МЫСЛИ ───
  { id:81, title:"Марио думает о жизни", desc:"Марио сидит у окна и думает — зачем он 40 лет спасает Пич.", mood:"философский", sign:"", visitors:[], action:"window-thinking", items:["window-rain","cup","deep-thought"], timeOfDay:"evening", doorState:"closed" },
  { id:82, title:"Экзистенциальный кризис", desc:"Марио понял что он персонаж игры. Стены — пиксели. Всё ненастоящее.", mood:"экзистенциальный", sign:"ЭТО РЕАЛЬНО?", visitors:[], action:"stare-wall", items:["pixel-wall","mirror","glitch"], timeOfDay:"night", doorState:"closed" },
  { id:83, title:"Старые фотографии", desc:"Марио нашёл альбом с фото из 1985 года. Он был таким молодым. 8 пикселей.", mood:"ностальгический", sign:"", visitors:[], action:"flip-album", items:["photo-album","8bit-photos","tear"], timeOfDay:"evening", doorState:"closed" },
  { id:84, title:"Марио пишет завещание", desc:"Марио решил написать завещание. Всё оставляет Луиджи. Кроме кепки.", mood:"драматичный", sign:"", visitors:[], action:"write-serious", items:["will-paper","pen","serious-face"], timeOfDay:"night", doorState:"closed" },
  { id:85, title:"Сон внутри сна", desc:"Марио не может понять — спит он или нет. Мир мерцает.", mood:"запутанный", sign:"", visitors:[], action:"confused-blink", items:["flickering-room","dream-bubble","inception"], timeOfDay:"night", doorState:"closed" },
  { id:86, title:"Письмо от самого себя", desc:"Марио нашёл письмо от себя из будущего. Там написано: 'Не ешь гриб'.", mood:"заинтригованный", sign:"", visitors:[], action:"read-confused", items:["future-letter","time-clock","warning"], timeOfDay:"day", doorState:"closed" },
  { id:87, title:"Марио считает монеты жизни", desc:"Марио подсчитал — он умирал 4,237 раз. Задумался о бессмертии.", mood:"мрачный", sign:"", visitors:[], action:"calculator", items:["tally-marks","calculator","life-counter"], timeOfDay:"night", doorState:"closed" },
  { id:88, title:"Разговор с зеркалом", desc:"Марио разговаривает со своим отражением. Отражение спорит.", mood:"сумасшедший", sign:"", visitors:[], action:"mirror-talk", items:["mirror","two-marios","argument"], timeOfDay:"night", doorState:"closed" },
  { id:89, title:"Марио и закат", desc:"Марио вышел на балкон и смотрит на закат. Тихо. Красиво. Одиноко.", mood:"меланхоличный", sign:"", visitors:[], action:"balcony-sunset", items:["sunset","railing","warm-light"], timeOfDay:"evening", doorState:"open" },
  { id:90, title:"Последний уровень", desc:"Марио чувствует что его история подходит к концу. Что дальше?", mood:"задумчивый", sign:"ФИНАЛ?", visitors:[], action:"sit-quiet", items:["flag-memory","sunset","peace"], timeOfDay:"evening", doorState:"closed" },

  // ─── 91-100: БЕЗУМИЕ И АБСУРД ───
  { id:91, title:"Труба ожила", desc:"Труба-дом Марио начала разговаривать. Просит не наступать на неё.", mood:"в шоке", sign:"", visitors:[], action:"talk-to-pipe", items:["talking-pipe","speech-bubble","wtf"], timeOfDay:"day", doorState:"open" },
  { id:92, title:"Дождь из монет", desc:"Из крана идут монеты вместо воды. Марио богатеет но не может помыться.", mood:"смешанный", sign:"", visitors:[], action:"catch-coins", items:["coin-faucet","bucket-coins","dirty-mario"], timeOfDay:"day", doorState:"closed" },
  { id:93, title:"Марио уменьшился", desc:"Марио случайно стал маленьким. Дом кажется гигантским. Кот его преследует.", mood:"в панике", sign:"", visitors:[], action:"run-tiny", items:["giant-furniture","cat","tiny-mario"], timeOfDay:"day", doorState:"closed" },
  { id:94, title:"Параллельный Марио", desc:"Из трубы вылез второй Марио. Они уставились друг на друга.", mood:"шокированный", sign:"", visitors:["mario-clone"], action:"stare-clone", items:["two-marios","mirror-effect","confusion"], timeOfDay:"day", doorState:"closed" },
  { id:95, title:"Дом летит", desc:"Дом Марио оторвался от земли и летит. Марио хватается за мебель.", mood:"в панике", sign:"ПОМОГИТЕ", visitors:[], action:"hold-furniture", items:["flying-house","clouds","floating-items"], timeOfDay:"day", doorState:"open" },
  { id:96, title:"Марио в пижаме", desc:"К Марио внезапно пришла целая делегация Тоадов. Он в пижаме.", mood:"сконфуженный", sign:"", visitors:["toad","toad","toad"], action:"hide-pajamas", items:["pajamas","delegation","embarrassment"], timeOfDay:"morning", doorState:"open" },
  { id:97, title:"Всё стало 8-битным", desc:"Весь дом стал 8-битным. Пиксели везде. Марио в растерянности.", mood:"дезориентированный", sign:"GLITCH", visitors:[], action:"pixel-world", items:["8bit-everything","glitch-effect","retro"], timeOfDay:"day", doorState:"closed" },
  { id:98, title:"Гриб-великан в гостиной", desc:"Гигантский гриб вырос прямо посреди гостиной. Пробил потолок.", mood:"обескураженный", sign:"", visitors:[], action:"stare-mushroom", items:["giant-mushroom","broken-ceiling","spores"], timeOfDay:"day", doorState:"closed" },
  { id:99, title:"Почта из других игр", desc:"Марио получает письма от героев других игр. Линк, Соник, Пакман.", mood:"популярный", sign:"ПОЧТА", visitors:[], action:"read-mail", items:["letters-pile","triforce","ring","pac-dot"], timeOfDay:"day", doorState:"closed" },
  { id:100, title:"Марио счастлив", desc:"Просто хороший день. Солнце, тишина, паста на плите, никто не похищен.", mood:"абсолютно-счастливый", sign:"♥", visitors:[], action:"happy-dance", items:["sunshine","pasta","peace","smile"], timeOfDay:"day", doorState:"closed" }
];
